import Head from "next/head";
import { TestPageBody } from "./body";

export default function TestPage() {
  console.log(window.location);
  return (
    <div>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestPageBody />
    </div>
  );
}
